#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

#
mod 'puppetlabs-ntp'
mod 'puppetlabs-firewall'
#mod 'puppetlabs-apache'
#
mod 'saz-timezone'
#
mod 'pdxcat-collectd',
  :git => 'git://github.com/pdxcat/puppet-module-collectd.git'
#
mod 'golja-influxdb'
#
mod 'echocat-graphite',
  :git => 'git://github.com/echocat/puppet-graphite.git'
#
mod 'bfraser/grafana'
