#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

#
mod 'puppetlabs-ntp'
mod 'puppetlabs-firewall'
#
mod 'thias/sysctl'
#
mod 'dhoppe/fail2ban'
#
mod 'saz-timezone'
#
mod 'pdxcat-collectd',
  :git => 'https://github.com/pdxcat/puppet-module-collectd.git'
#
mod 'golja-influxdb'
#
mod 'bfraser/grafana'
